name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode
        run: sudo xcode-select --switch /Applications/Xcode_15.0.app

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod install

      - name: Build and test
        run: |
          xcodebuild clean build test \
          -workspace FireBase.xcworkspace \
          -scheme FireBase \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15'
