name: iOS CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod install

      - name: List available schemes
        run: |
          xcodebuild -workspace FireBase.xcworkspace -list

     
      - name: Build iOS App
        run: |
          xcodebuild -workspace FireBase.xcworkspace \
                     -scheme FireBase \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
                     clean build
